Fix redeclaration of secure string functions
MinGW-W64 already provides secure string functions "strcpy_s",
"strcat_s", "strncpy_s", "sprintf_s". Functions presence can can be
tested using MINGW_HAS_SECURE_API preprocessor definition.

Unfortunately, function prototypes from c-shared-utility are conflicting
with prototypes provided by MinGW-W64, which causes the following
compile errors:

crt_abstractions.h:96:12: error: 'strcpy_s' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int strcpy_s(char* dst, size_t dstSizeInBytes, const char* src);
            ^~~~~~~~
crt_abstractions.h:97:12: error: 'strcat_s' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int strcat_s(char* dst, size_t dstSizeInBytes, const char* src);
            ^~~~~~~~
crt_abstractions.h:98:12: error: 'strncpy_s' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int strncpy_s(char* dst, size_t dstSizeInBytes, const char* src, size_t maxCount);
            ^~~~~~~~~
crt_abstractions.h:99:12: error: 'sprintf_s' redeclared without dllimport attribute: previous dllimport ignored [-Werror=attributes]
 extern int sprintf_s(char* dst, size_t dstSizeInBytes, const char* format, ...);
            ^~~~~~~~~

Fix error by disabling c-shared-utility functions if the same are
provided by MinGW-W64.

Signed-off-by: Vitaly Kuzmichev <vkuzmichev@dev.rtsoft.ru>